[extend]
useDefault = true

[allowlist]
paths = [
    '''.*\/.run\/.*''',
    '''.*\/.local-resources\/.*''',
    '''.*\/.yarn\/.*''',
    '''.*\/.vite-cache\/.*''',
    '''.run\/.*''',
    '''.local-resources\/.*''',
    '''.yarn\/.*''',
    '''.vite-cache\/.*''',
]
