# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: golang-graphql-example
before:
  hooks:
    - make code/clean
    - make setup/dep/install
builds:
  - main: ./cmd/golang-graphql-example
    binary: golang-graphql-example
    flags:
      - -trimpath
    #   - -mod=vendor
    ldflags:
      - -extldflags "-static"
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.Version={{ .Tag }}
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.GitCommit={{ .ShortCommit }}
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.BuildDate={{ .Date }}
      # Clear the "unreleased" string in Metadata
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.Metadata=
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: oxyno-zeta
    name: golang-graphql-example
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - golang-graphql-example
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-amd64"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
      - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"
  - goos: linux
    goarch: arm
    goarm: 6
    ids:
      - golang-graphql-example
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv6"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
      - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"
  - goos: linux
    goarch: arm
    goarm: 7
    ids:
      - golang-graphql-example
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv7"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
      - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"
  - goos: linux
    goarch: arm64
    ids:
      - golang-graphql-example
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-arm64"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
      - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"

docker_manifests:
  - name_template: oxynozeta/golang-graphql-example:latest
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-amd64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-arm64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv6"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv7"
  - name_template: "oxynozeta/golang-graphql-example:{{ .Version }}"
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-amd64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-arm64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv6"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv7"
  - name_template: "oxynozeta/golang-graphql-example:{{ .Major }}"
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-amd64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-arm64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv6"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv7"
  - name_template: "oxynozeta/golang-graphql-example:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "oxynozeta/golang-graphql-example:{{ .Version }}-amd64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-arm64"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv6"
      - "oxynozeta/golang-graphql-example:{{ .Version }}-armv7"
