# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: golang-graphql-example
before:
  hooks:
    - make code/clean
    - make setup/dep/install
builds:
  - main: ./cmd/golang-graphql-example
    binary: golang-graphql-example
    flags:
      - -trimpath
    #   - -mod=vendor
    ldflags:
      - -extldflags "-static"
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.Version={{ .Tag }}
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.GitCommit={{ .ShortCommit }}
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.BuildDate={{ .Date }}
      # Clear the "unreleased" string in Metadata
      - -X github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/version.Metadata=
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - ppc64le
      - s390x
    goarm:
      - 6
      - 7
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: oxyno-zeta
    name: golang-graphql-example
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - golang-graphql-example
    image_templates:
      - "oxynozeta/golang-graphql-example:latest"
      - "oxynozeta/golang-graphql-example:{{ .Version }}"
      - "oxynozeta/golang-graphql-example:{{ .Major }}"
      - "oxynozeta/golang-graphql-example:{{ .Major }}.{{ .Minor }}"
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
      - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"
    extra_files:
      - templates/
  # Disabled because can't build arm on release laptop
  # - goos: linux
  #   goarch: arm
  #   goarm: 6
  #   binaries:
  #     - golang-graphql-example
  #   image_templates:
  #     - "oxynozeta/golang-graphql-example:latest-armv6"
  #     - "oxynozeta/golang-graphql-example:{{ .Version }}-armv6"
  #     - "oxynozeta/golang-graphql-example:{{ .Major }}-armv6"
  #     - "oxynozeta/golang-graphql-example:{{ .Major }}.{{ .Minor }}-armv6"
  #   skip_push: false
  #   dockerfile: Dockerfile.armv6
  #   build_flag_templates:
  #     - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
  #     - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"
  #   extra_files:
  #     - templates/
  # - goos: linux
  #   goarch: arm
  #   goarm: 7
  #   binaries:
  #     - golang-graphql-example
  #   image_templates:
  #     - "oxynozeta/golang-graphql-example:latest-armv7"
  #     - "oxynozeta/golang-graphql-example:{{ .Version }}-armv7"
  #     - "oxynozeta/golang-graphql-example:{{ .Major }}-armv7"
  #     - "oxynozeta/golang-graphql-example:{{ .Major }}.{{ .Minor }}-armv7"
  #   skip_push: false
  #   dockerfile: Dockerfile.armv7
  #   build_flag_templates:
  #     - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
  #     - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"
  #   extra_files:
  #     - templates/
  # - goos: linux
  #   goarch: arm64
  #   binaries:
  #     - golang-graphql-example
  #   image_templates:
  #     - "oxynozeta/golang-graphql-example:latest-arm64"
  #     - "oxynozeta/golang-graphql-example:{{ .Version }}-arm64"
  #     - "oxynozeta/golang-graphql-example:{{ .Major }}-arm64"
  #     - "oxynozeta/golang-graphql-example:{{ .Major }}.{{ .Minor }}-arm64"
  #   skip_push: false
  #   dockerfile: Dockerfile.arm64
  #   build_flag_templates:
  #     - "--label=oxyno-zeta.golang-graphql-example.version={{ .Version }}"
  #     - "--label=oxyno-zeta.golang-graphql-example.name={{ .ProjectName }}"
  #   extra_files:
  #     - templates/
