#:schema https://mise.jdx.dev/schema/mise.json

[tools]
go = '1.24.1'
golangci-lint = "2.0.0"
# renovate: datasource=github-tags depName=gotestyourself/gotestsum
gotestsum = "v1.12.0"
# renovate: datasource=github-tags depName=99designs/gqlgen
"go:github.com/99designs/gqlgen" = "v0.17.66"
# renovate: datasource=go depName=go.uber.org/mock/mockgen
"go:go.uber.org/mock/mockgen" = "v0.5.0"
# renovate: datasource=go depName=golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment
# "go:golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment" = "v0.31.0"
# renovate: datasource=github-tags depName=boumenot/gocover-cobertura
"go:github.com/boumenot/gocover-cobertura" = "v1.3.0"
# renovate: datasource=github-tags depName=mitchellh/gox
"go:github.com/mitchellh/gox" = "v1.0.1"
