#:schema https://mise.jdx.dev/schema/mise.json

[tools]
go = '1.25.1'
golangci-lint = "2.5.0"
# renovate: datasource=github-tags depName=gotestyourself/gotestsum
gotestsum = "1.13.0"
# renovate: datasource=github-tags depName=99designs/gqlgen
"go:github.com/99designs/gqlgen" = "v0.17.81"
# renovate: datasource=go depName=go.uber.org/mock/mockgen
"go:go.uber.org/mock/mockgen" = "v0.6.0"
# renovate: datasource=go depName=golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment
# "go:golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment" = "v0.37.0"
# renovate: datasource=github-tags depName=boumenot/gocover-cobertura
"go:github.com/boumenot/gocover-cobertura" = "v1.4.0"
# renovate: datasource=github-tags depName=mitchellh/gox
"go:github.com/mitchellh/gox" = "v1.0.1"
