// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/tracing (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	graphql "github.com/99designs/gqlgen/graphql"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	opentracing "github.com/opentracing/opentracing-go"
	tracing "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/tracing"
	gorm "gorm.io/gorm"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DatabaseMiddleware mocks base method.
func (m *MockService) DatabaseMiddleware() gorm.Plugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseMiddleware")
	ret0, _ := ret[0].(gorm.Plugin)
	return ret0
}

// DatabaseMiddleware indicates an expected call of DatabaseMiddleware.
func (mr *MockServiceMockRecorder) DatabaseMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseMiddleware", reflect.TypeOf((*MockService)(nil).DatabaseMiddleware))
}

// ExtractFromHTTPHeaderAndStartSpan mocks base method.
func (m *MockService) ExtractFromHTTPHeaderAndStartSpan(arg0 http.Header, arg1 string) (tracing.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFromHTTPHeaderAndStartSpan", arg0, arg1)
	ret0, _ := ret[0].(tracing.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFromHTTPHeaderAndStartSpan indicates an expected call of ExtractFromHTTPHeaderAndStartSpan.
func (mr *MockServiceMockRecorder) ExtractFromHTTPHeaderAndStartSpan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFromHTTPHeaderAndStartSpan", reflect.TypeOf((*MockService)(nil).ExtractFromHTTPHeaderAndStartSpan), arg0, arg1)
}

// ExtractFromTextMapAndStartSpan mocks base method.
func (m *MockService) ExtractFromTextMapAndStartSpan(arg0 map[string]string, arg1 string) (tracing.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFromTextMapAndStartSpan", arg0, arg1)
	ret0, _ := ret[0].(tracing.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFromTextMapAndStartSpan indicates an expected call of ExtractFromTextMapAndStartSpan.
func (mr *MockServiceMockRecorder) ExtractFromTextMapAndStartSpan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFromTextMapAndStartSpan", reflect.TypeOf((*MockService)(nil).ExtractFromTextMapAndStartSpan), arg0, arg1)
}

// GetTracer mocks base method.
func (m *MockService) GetTracer() opentracing.Tracer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracer")
	ret0, _ := ret[0].(opentracing.Tracer)
	return ret0
}

// GetTracer indicates an expected call of GetTracer.
func (mr *MockServiceMockRecorder) GetTracer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracer", reflect.TypeOf((*MockService)(nil).GetTracer))
}

// GraphqlMiddleware mocks base method.
func (m *MockService) GraphqlMiddleware() graphql.HandlerExtension {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GraphqlMiddleware")
	ret0, _ := ret[0].(graphql.HandlerExtension)
	return ret0
}

// GraphqlMiddleware indicates an expected call of GraphqlMiddleware.
func (mr *MockServiceMockRecorder) GraphqlMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GraphqlMiddleware", reflect.TypeOf((*MockService)(nil).GraphqlMiddleware))
}

// HTTPMiddleware mocks base method.
func (m *MockService) HTTPMiddleware(arg0 func(context.Context) string) gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPMiddleware", arg0)
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// HTTPMiddleware indicates an expected call of HTTPMiddleware.
func (mr *MockServiceMockRecorder) HTTPMiddleware(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPMiddleware", reflect.TypeOf((*MockService)(nil).HTTPMiddleware), arg0)
}

// Reload mocks base method.
func (m *MockService) Reload() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reload indicates an expected call of Reload.
func (mr *MockServiceMockRecorder) Reload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockService)(nil).Reload))
}

// StartChildTraceOrTraceFromContext mocks base method.
func (m *MockService) StartChildTraceOrTraceFromContext(arg0 context.Context, arg1 string) tracing.Trace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartChildTraceOrTraceFromContext", arg0, arg1)
	ret0, _ := ret[0].(tracing.Trace)
	return ret0
}

// StartChildTraceOrTraceFromContext indicates an expected call of StartChildTraceOrTraceFromContext.
func (mr *MockServiceMockRecorder) StartChildTraceOrTraceFromContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartChildTraceOrTraceFromContext", reflect.TypeOf((*MockService)(nil).StartChildTraceOrTraceFromContext), arg0, arg1)
}

// StartTrace mocks base method.
func (m *MockService) StartTrace(arg0 string) tracing.Trace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTrace", arg0)
	ret0, _ := ret[0].(tracing.Trace)
	return ret0
}

// StartTrace indicates an expected call of StartTrace.
func (mr *MockServiceMockRecorder) StartTrace(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTrace", reflect.TypeOf((*MockService)(nil).StartTrace), arg0)
}
