// Code generated by daogen, DO NOT EDIT.
package graphqlgenerated

import (
	models0 "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/business/todos/models"
	pagination "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/database/pagination"
	model "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/server/graphql/model"
	utils "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/server/graphql/utils"
)

func MapTodoConnection(list []*models0.Todo, pageOut *pagination.PageOutput) (*model.TodoConnection, error) {
	edges := make([]*model.TodoEdge, len(list))

	for i, v := range list {
		cursor := utils.GetPaginateCursor(i, pageOut.Skip)

		edges[i] = &model.TodoEdge{
			Cursor: cursor,
			Node:   v,
		}
	}

	res := &model.TodoConnection{
		Edges: edges,
		PageInfo: &utils.PageInfo{
			HasNextPage:     pageOut.HasNext,
			HasPreviousPage: pageOut.HasPrevious,
		},
	}

	return res, nil
}
