// Code generated by daogen, DO NOT EDIT.
package graphqlgenerated

import (
	models0 "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/business/todos/models"
	pagination "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/database/pagination"
	model "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/server/graphql/model"
	utils "github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/server/graphql/utils"
)

func MapTodoConnection(list []*models0.Todo, page *pagination.PageOutput) (*model.TodoConnection, error) {
	res := &model.TodoConnection{
		Edges: []*model.TodoEdge{},
		PageInfo: &utils.PageInfo{
			HasNextPage:     page.HasNext,
			HasPreviousPage: page.HasPrevious,
		},
	}

	return res, nil
}
