// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/metrics (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	graphql "github.com/99designs/gqlgen/graphql"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DatabaseMiddleware mocks base method.
func (m *MockService) DatabaseMiddleware(arg0 string) gorm.Plugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseMiddleware", arg0)
	ret0, _ := ret[0].(gorm.Plugin)
	return ret0
}

// DatabaseMiddleware indicates an expected call of DatabaseMiddleware.
func (mr *MockServiceMockRecorder) DatabaseMiddleware(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseMiddleware", reflect.TypeOf((*MockService)(nil).DatabaseMiddleware), arg0)
}

// GraphqlMiddleware mocks base method.
func (m *MockService) GraphqlMiddleware() graphql.HandlerExtension {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GraphqlMiddleware")
	ret0, _ := ret[0].(graphql.HandlerExtension)
	return ret0
}

// GraphqlMiddleware indicates an expected call of GraphqlMiddleware.
func (mr *MockServiceMockRecorder) GraphqlMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GraphqlMiddleware", reflect.TypeOf((*MockService)(nil).GraphqlMiddleware))
}

// IncreaseFailedAMQPConsumedMessage mocks base method.
func (m *MockService) IncreaseFailedAMQPConsumedMessage(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseFailedAMQPConsumedMessage", arg0, arg1, arg2)
}

// IncreaseFailedAMQPConsumedMessage indicates an expected call of IncreaseFailedAMQPConsumedMessage.
func (mr *MockServiceMockRecorder) IncreaseFailedAMQPConsumedMessage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseFailedAMQPConsumedMessage", reflect.TypeOf((*MockService)(nil).IncreaseFailedAMQPConsumedMessage), arg0, arg1, arg2)
}

// IncreaseFailedAMQPPublishedMessage mocks base method.
func (m *MockService) IncreaseFailedAMQPPublishedMessage(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseFailedAMQPPublishedMessage", arg0, arg1)
}

// IncreaseFailedAMQPPublishedMessage indicates an expected call of IncreaseFailedAMQPPublishedMessage.
func (mr *MockServiceMockRecorder) IncreaseFailedAMQPPublishedMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseFailedAMQPPublishedMessage", reflect.TypeOf((*MockService)(nil).IncreaseFailedAMQPPublishedMessage), arg0, arg1)
}

// IncreaseSuccessfullyAMQPConsumedMessage mocks base method.
func (m *MockService) IncreaseSuccessfullyAMQPConsumedMessage(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseSuccessfullyAMQPConsumedMessage", arg0, arg1, arg2)
}

// IncreaseSuccessfullyAMQPConsumedMessage indicates an expected call of IncreaseSuccessfullyAMQPConsumedMessage.
func (mr *MockServiceMockRecorder) IncreaseSuccessfullyAMQPConsumedMessage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseSuccessfullyAMQPConsumedMessage", reflect.TypeOf((*MockService)(nil).IncreaseSuccessfullyAMQPConsumedMessage), arg0, arg1, arg2)
}

// IncreaseSuccessfullyAMQPPublishedMessage mocks base method.
func (m *MockService) IncreaseSuccessfullyAMQPPublishedMessage(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseSuccessfullyAMQPPublishedMessage", arg0, arg1)
}

// IncreaseSuccessfullyAMQPPublishedMessage indicates an expected call of IncreaseSuccessfullyAMQPPublishedMessage.
func (mr *MockServiceMockRecorder) IncreaseSuccessfullyAMQPPublishedMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseSuccessfullyAMQPPublishedMessage", reflect.TypeOf((*MockService)(nil).IncreaseSuccessfullyAMQPPublishedMessage), arg0, arg1)
}

// Instrument mocks base method.
func (m *MockService) Instrument(arg0 string, arg1 bool) gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instrument", arg0, arg1)
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// Instrument indicates an expected call of Instrument.
func (mr *MockServiceMockRecorder) Instrument(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instrument", reflect.TypeOf((*MockService)(nil).Instrument), arg0, arg1)
}

// PrometheusHTTPHandler mocks base method.
func (m *MockService) PrometheusHTTPHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrometheusHTTPHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// PrometheusHTTPHandler indicates an expected call of PrometheusHTTPHandler.
func (mr *MockServiceMockRecorder) PrometheusHTTPHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrometheusHTTPHandler", reflect.TypeOf((*MockService)(nil).PrometheusHTTPHandler))
}
