// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/metrics (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	graphql "github.com/99designs/gqlgen/graphql"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DatabaseMiddleware mocks base method.
func (m *MockClient) DatabaseMiddleware(arg0 string) gorm.Plugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseMiddleware", arg0)
	ret0, _ := ret[0].(gorm.Plugin)
	return ret0
}

// DatabaseMiddleware indicates an expected call of DatabaseMiddleware.
func (mr *MockClientMockRecorder) DatabaseMiddleware(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseMiddleware", reflect.TypeOf((*MockClient)(nil).DatabaseMiddleware), arg0)
}

// GraphqlMiddleware mocks base method.
func (m *MockClient) GraphqlMiddleware() graphql.HandlerExtension {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GraphqlMiddleware")
	ret0, _ := ret[0].(graphql.HandlerExtension)
	return ret0
}

// GraphqlMiddleware indicates an expected call of GraphqlMiddleware.
func (mr *MockClientMockRecorder) GraphqlMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GraphqlMiddleware", reflect.TypeOf((*MockClient)(nil).GraphqlMiddleware))
}

// IncreaseFailedAMQPConsumedMessage mocks base method.
func (m *MockClient) IncreaseFailedAMQPConsumedMessage(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseFailedAMQPConsumedMessage", arg0, arg1, arg2)
}

// IncreaseFailedAMQPConsumedMessage indicates an expected call of IncreaseFailedAMQPConsumedMessage.
func (mr *MockClientMockRecorder) IncreaseFailedAMQPConsumedMessage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseFailedAMQPConsumedMessage", reflect.TypeOf((*MockClient)(nil).IncreaseFailedAMQPConsumedMessage), arg0, arg1, arg2)
}

// IncreaseFailedAMQPPublishedMessage mocks base method.
func (m *MockClient) IncreaseFailedAMQPPublishedMessage(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseFailedAMQPPublishedMessage", arg0, arg1)
}

// IncreaseFailedAMQPPublishedMessage indicates an expected call of IncreaseFailedAMQPPublishedMessage.
func (mr *MockClientMockRecorder) IncreaseFailedAMQPPublishedMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseFailedAMQPPublishedMessage", reflect.TypeOf((*MockClient)(nil).IncreaseFailedAMQPPublishedMessage), arg0, arg1)
}

// IncreaseSuccessfullyAMQPConsumedMessage mocks base method.
func (m *MockClient) IncreaseSuccessfullyAMQPConsumedMessage(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseSuccessfullyAMQPConsumedMessage", arg0, arg1, arg2)
}

// IncreaseSuccessfullyAMQPConsumedMessage indicates an expected call of IncreaseSuccessfullyAMQPConsumedMessage.
func (mr *MockClientMockRecorder) IncreaseSuccessfullyAMQPConsumedMessage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseSuccessfullyAMQPConsumedMessage", reflect.TypeOf((*MockClient)(nil).IncreaseSuccessfullyAMQPConsumedMessage), arg0, arg1, arg2)
}

// IncreaseSuccessfullyAMQPPublishedMessage mocks base method.
func (m *MockClient) IncreaseSuccessfullyAMQPPublishedMessage(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseSuccessfullyAMQPPublishedMessage", arg0, arg1)
}

// IncreaseSuccessfullyAMQPPublishedMessage indicates an expected call of IncreaseSuccessfullyAMQPPublishedMessage.
func (mr *MockClientMockRecorder) IncreaseSuccessfullyAMQPPublishedMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseSuccessfullyAMQPPublishedMessage", reflect.TypeOf((*MockClient)(nil).IncreaseSuccessfullyAMQPPublishedMessage), arg0, arg1)
}

// Instrument mocks base method.
func (m *MockClient) Instrument(arg0 string) gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instrument", arg0)
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// Instrument indicates an expected call of Instrument.
func (mr *MockClientMockRecorder) Instrument(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instrument", reflect.TypeOf((*MockClient)(nil).Instrument), arg0)
}

// PrometheusHTTPHandler mocks base method.
func (m *MockClient) PrometheusHTTPHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrometheusHTTPHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// PrometheusHTTPHandler indicates an expected call of PrometheusHTTPHandler.
func (mr *MockClientMockRecorder) PrometheusHTTPHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrometheusHTTPHandler", reflect.TypeOf((*MockClient)(nil).PrometheusHTTPHandler))
}
