package main

import (
	"os"
	"path"
	"strconv"

	"emperror.dev/errors"
	"github.com/dave/jennifer/jen"
)

const (
	EdgesStructureKeyName                  = "Edges"
	PageInfoStructureKeyName               = "PageInfo"
	PageInfoUtilsStructureName             = "PageInfo"
	PageInfoUtilsHasNextPageKeyName        = "HasNextPage"
	PageInfoUtilsHasPreviousPageKeyName    = "HasPreviousPage"
	PaginationPageOutputStructureName      = "PageOutput"
	PaginationPageOutputHasPreviousKeyName = "HasPrevious"
	PaginationPageOutputHasNextKeyName     = "HasNext"
)

func generate(cfg *Config) error {
	// Create directory
	err := os.MkdirAll(cfg.Path, os.ModePerm)
	// Check error
	if err != nil {
		return errors.WithStack(err)
	}

	// Create new file
	f := jen.NewFile(cfg.PackageName)

	// A comment to mark the file as generated
	f.PackageComment("Code generated by daogen, DO NOT EDIT.")

	addImports(f, cfg.Connections, cfg.NeededPackages.GqlgenModelPackage)

	for _, v := range cfg.Connections {
		generateConnectionTransform(f, v, cfg.NeededPackages)
	}

	// Generate path
	p := path.Join(cfg.Path, "generated.go")

	// Save
	err = f.Save(p)
	// Check error
	if err != nil {
		return errors.WithStack(err)
	}

	// Default
	return nil
}

func addImports(f *jen.File, list []*ConnectionCfg, gqlgenModelPackage string) {
	// Cache imports to avoid duplicates
	cache := map[string]string{}

	f.ImportAlias(gqlgenModelPackage, "model")

	for i, m := range list {
		// Get from cache
		_, found := cache[m.Package]

		// If not found
		if !found {
			// Alias
			f.ImportAlias(m.Package, "models"+strconv.Itoa(i))
			// Save in cache
			cache[m.Package] = ""
		}
	}
}

func generateConnectionTransform(f *jen.File, conn *ConnectionCfg, neededPackages *NeededPackagesCfg) {
	f.Func().Id("Map"+conn.StructureName+"Connection").Params(
		jen.Id("list").Index().Op("*").Qual(conn.Package, conn.StructureName),
		jen.Id("page").Op("*").Qual(neededPackages.Pagination, PaginationPageOutputStructureName),
	).Parens(jen.List(
		jen.Op("*").Qual(neededPackages.GqlgenModelPackage, conn.StructureName+"Connection"),
		jen.Error(),
	)).Block(
		jen.Id("res").Op(":=").Op("&").Qual(neededPackages.GqlgenModelPackage, conn.StructureName+"Connection").Values(jen.Dict{
			jen.Id(EdgesStructureKeyName): jen.Index().Op("*").Qual(neededPackages.GqlgenModelPackage, conn.StructureName+"Edge").Values(),
			jen.Id(PageInfoStructureKeyName): jen.Op("&").Qual(neededPackages.GraphqlUtils, PageInfoUtilsStructureName).Values(jen.Dict{
				jen.Id(PageInfoUtilsHasNextPageKeyName):     jen.Id("page").Op(".").Id(PaginationPageOutputHasNextKeyName),
				jen.Id(PageInfoUtilsHasPreviousPageKeyName): jen.Id("page").Op(".").Id(PaginationPageOutputHasPreviousKeyName),
			}),
		}),
		jen.Line(),

		jen.Return(jen.Id("res"), jen.Nil()),
	)
}
