// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/business/todos/models"
	"github.com/oxyno-zeta/golang-graphql-example/pkg/golang-graphql-example/server/graphql/utils"
)

type Mutation struct {
}

type NewTodo struct {
	Text string `json:"text"`
}

type Query struct {
}

type TodoConnection struct {
	Edges    []*TodoEdge     `json:"edges,omitempty"`
	PageInfo *utils.PageInfo `json:"pageInfo"`
}

type TodoEdge struct {
	Cursor string       `json:"cursor"`
	Node   *models.Todo `json:"node,omitempty"`
}

type UpdateTodo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
