// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text string `json:"text"`
}

type Todo struct {
	ID           string `json:"id"`
	Text         string `json:"text"`
	Done         bool   `json:"done"`
	CreationDate string `json:"creationDate"`
}

type UpdateTodo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
