name: "Add size label"
on: pull_request

permissions:
  contents: read

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.5.7
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
